wb_dcache: Make AXI data width parametrisable
pulp-platform/cva6 pull request #1
Opened 2021-11-18 01:14 UTC by niwis

2021-11-22 20:23 UTC, zarubaf requested changes
Almost good to go! Thanks

2021-11-22 20:23 UTC, zarubaf commented on include/ariane_pkg.sv
> +      return (address >= base) && (address < (65'(base)+len));
Why 65, is that zero-extended?

2021-11-22 20:23 UTC, zarubaf commented on include/ariane_pkg.sv
> +    localparam int unsigned ICACHE_LINE_WIDTH  = 512; // in bit
I think we can leave it at the default of 256? I assume that is an artifact of the trials, right?

2021-11-22 20:23 UTC, zarubaf commented on src/axi_adapter.sv
> +    axi_req_o.aw.addr   = addr_i[AXI_DATA_WIDTH-1:0];
I guess:
```suggestion
    axi_req_o.aw.addr   = addr_i[AXI_ADDR_WIDTH-1:0];
```

2021-11-22 20:23 UTC, zarubaf commented on src/axi_adapter.sv
> +    axi_req_o.ar.addr   = (CRITICAL_WORD_FIRST || type_i == ariane_axi::SINGLE_REQ) ? addr_i[AXI_DATA_WIDTH-1:0] : { addr_i[AXI_DATA_WIDTH-1:CACHELINE_BYTE_OFFSET], {{CACHELINE_BYTE_OFFSET}{1'b0}}};
```suggestion
    axi_req_o.ar.addr   = (CRITICAL_WORD_FIRST || type_i == ariane_axi::SINGLE_REQ) ? addr_i[AXI_ADDR_WIDTH-1:0] : { addr_i[AXI_ADDR_WIDTH-1:CACHELINE_BYTE_OFFSET], {{CACHELINE_BYTE_OFFSET}{1'b0}}};
```

2021-11-22 20:23 UTC, zarubaf commented on src/cache_subsystem/miss_handler.sv
> +        .id_i                  ( {{AXI_ID_WIDTH-4{1'b0}}, 2'b10, id_fsm_bypass} ),
Technically I think 
```suggestion
        .id_i                  ( $unsigned({2'b10, id_fsm_bypass})),
```
should do the same. Either way, that's good.

2021-11-22 20:24 UTC, zarubaf commented
Never mind, I've confused this with the original repo (seem to have the notifications on for both). Feel free to ignore everything and I will unsubscribe from this repo :-)

2021-11-22 21:34 UTC, niwis commented
@zarubaf Oops sorry for that, but thanks anyways for the review. This will probably land upstream at some point, anyways :-)

2022-11-15 18:41 UTC, niwis commented
Merged upstream: https://github.com/openhwgroup/cva6/pull/982

2022-11-15 18:41 UTC, closed without merging