Add synchronous clear.
pulp-platform/cva6 pull request #42
Opened 2024-02-28 13:55 UTC by yvantor

Synchronous clear is useful for applications where the core internal status must be flushed from the outside (for example, a redundant unit detects an error and needs to flush the core to bring its internals to a clear state), without compromising the regular asynchronous reset path.

2024-03-04 15:31 UTC, niwis requested changes
Hi Yvan, thanks for the PR. I have just a couple of comments.

We have been planning for a while to change to the common cells register macros (https://github.com/pulp-platform/common_cells/blob/master/include/common_cells/registers.svh). That would give more flexibility when choosing FFs but I see that this would be out of the scope for this PR.

2024-03-04 15:31 UTC, niwis commented on core/cva6.sv
> +      rst_uarch_n <= rst_uarch_controller_n & ~clear_i;
`rst_uarch_n` is asynchronous. There are some hazards when driving this with a synchronous signal (e.g. glitches). Are you sure you need to reset non-architected state?

2024-03-04 15:31 UTC, niwis commented on core/issue_read_operands.sv
This will break `fence.t`, which resets all non-architectural, microarchitectural state while preserving the architectural state (which you are clearing here). could you connect this directly to `clear_i` from the top-level?

2024-03-04 15:31 UTC, niwis commented on core/cva6.sv
> +      rst_uarch_n <= rst_uarch_controller_n & ~clear_i;
If so, we need to make sure that this is stable e.g. by latching the signal

2024-03-04 16:19 UTC, yvantor commented on common/local/util/sram_pulp.sv
> +    parameter SIM_INIT   = "zeros",
It is not strictly needed for this PR, no. I swapped this when working on lockstepped redundant execution. In that case if the caches or any memories propagate Xs to the checker that controls the buses, it might have unwanted behaviour (also during RTL simulation). Since memory macros never have undefined states (would be either initialized at random values or at 0), to reproduce a scenario that is more similar to what we would have on the silicon I changed the init parameter. We could do this also in other ways (preloading in testbenches) or anyway remove this from this PR.

2024-03-04 16:21 UTC, yvantor commented on core/cva6.sv
> +      rst_uarch_n <= rst_uarch_controller_n & ~clear_i;
Did not figure out it to be asynchronous, I will tackle this differently.

2024-03-05 17:40 UTC, yvantor commented
@niwis turning this to draft after related discussion.

2024-05-11 14:11 UTC, yvantor commented
Hey Nils, I mark this as ready for review even though some work still needs to be done. I have two questions, if you could provide a few hints that would be greatly appreciated.

* It is not super clear to me what is going wrong with the CI. The execute-riscv-tests terminates with [two errors](https://github.com/pulp-platform/cva6/actions/runs/9028095974/job/24808527749?pr=42#step:4:471) but I could not spot any error message in the log. There are only [WIDTHTRUNC](https://github.com/pulp-platform/cva6/actions/runs/9028095974/job/24808527749?pr=42#step:4:71) and [WIDTHEXPAND](https://github.com/pulp-platform/cva6/actions/runs/9028095974/job/24808527749?pr=42#step:4:93) warnings on parameters I am quite sure I did not touch, do you have suggestions on how to fix this?
* For the Cheshire integration, the CI checks out from a [tag](https://github.com/pulp-platform/cheshire/tree/cva6/pulp-v1.0.0-rel) that is not keeping track of several things (for example the fact that the common_cells version changed and there are some new flip flops macros that cannot be found and break the code build). For now I am making an integration branch into Cheshire, I was curious to know if this thing can be automatized further.

Thank you!

2024-05-12 20:09 UTC, yvantor commented
> Hey Nils, I mark this as ready for review even though some work still needs to be done. I have two questions, if you could provide a few hints that would be greatly appreciated.
> 
>     * It is not super clear to me what is going wrong with the CI. The execute-riscv-tests terminates with [two errors](https://github.com/pulp-platform/cva6/actions/runs/9028095974/job/24808527749?pr=42#step:4:471) but I could not spot any error message in the log. There are only [WIDTHTRUNC](https://github.com/pulp-platform/cva6/actions/runs/9028095974/job/24808527749?pr=42#step:4:71) and [WIDTHEXPAND](https://github.com/pulp-platform/cva6/actions/runs/9028095974/job/24808527749?pr=42#step:4:93) warnings on parameters I am quite sure I did not touch, do you have suggestions on how to fix this?
> 
>     * For the Cheshire integration, the CI checks out from a [tag](https://github.com/pulp-platform/cheshire/tree/cva6/pulp-v1.0.0-rel) that is not keeping track of several things (for example the fact that the common_cells version changed and there are some new flip flops macros that cannot be found and break the code build). For now I am making an integration branch into Cheshire, I was curious to know if this thing can be automatized further.
> 
> 
> Thank you!

Edit: I think the CI now works, there is still the issue of automatically testing the integration into Cheshire. The branch where I tested it is [this](https://github.com/pulp-platform/cheshire/tree/yt/cva6-clear).

2024-05-13 17:09 UTC, niwis commented
Hi @yvantor,

- regarding build-riscv-tests, the hypervisor test ref was deleted upstream. I have fixed this in https://github.com/pulp-platform/cva6/commit/84422f0c156f596744965c362f6e417319cbe1af. Rebasing onto `pulp-v1` should fix this.

- regarding execute-riscv-tests, [here](https://github.com/pulp-platform/cva6/actions/runs/9053882291/job/24873359549?pr=42#step:4:137) seems to be an error with type conversions (although it looks good to me on a first look). Perhaps you have to add a typecast.

- regarding CI integration, this looks indeed like an issue with our FPGA server. I'll look into it.

2024-05-13 22:03 UTC, yvantor commented
> Hi @yvantor,
> 
>     * regarding build-riscv-tests, the hypervisor test ref was deleted upstream. I have fixed this in [84422f0](https://github.com/pulp-platform/cva6/commit/84422f0c156f596744965c362f6e417319cbe1af). Rebasing onto `pulp-v1` should fix this.
> 
>     * regarding execute-riscv-tests, [here](https://github.com/pulp-platform/cva6/actions/runs/9053882291/job/24873359549?pr=42#step:4:137) seems to be an error with type conversions (although it looks good to me on a first look). Perhaps you have to add a typecast.
> 
>     * regarding cheshire integration, this looks indeed like an issue with our FPGA server. I'll look into it.

Thanks for the feedback, should be fine now!

2026-05-28 09:01 UTC, ezelioli commented
Closing as it targets outdated branch

2026-05-28 09:01 UTC, closed without merging