Add `vCLIC` interface and logic
pulp-platform/cva6 pull request #44
Opened 2024-03-04 14:34 UTC by alex96295

This PR adds support for virtualized interrupts handled by the RISC-V CLIC interface.

@ezelioli this is the reference PR for this feature, to be updated in Cheshire and other systems using CVA6 + CLIC with virtual extensions enabled for the latter

It would be good if you could use this branch to run your tests, so we see if I missed something during cherry-picking (there were a lot of conflicts because the current codebase has different indentation, causing false negatives)

@ezelioli @niwis we should try to converge on this ASAP

2024-03-05 14:54 UTC, alex96295 commented
> FPGA implementation fails because `priv_lvl` and `trap_to_v` are missing in this assignment
> 
> https://github.com/pulp-platform/cva6/blob/eff9be562c44d1c6f8cf226879f90bbf7f254531/core/acc_dispatcher.sv#L268-L275

Thanks, will fix :)

2024-03-07 15:47 UTC, alex96295 commented
LGTM for me @niwis, maybe we can do some squashing or squash-and-merge, but functionally it's ready for merge

2024-03-16 15:36 UTC, niwis requested changes
Thanks a lot @ezelioli and @alex96295 for the extensions and rebase! I have a few general comments and suggestions, the rest in-line.

1. It seems like of the changes would generally be useful for H extension (also without CLIC). In particular, I'm thinking of a) tracing virtualisation mode, and b) Fixing H interrupt delegation. Do you think you could open dedicated PRs for these changes to this repo and Bruno's "upstream" [H-ext branch](https://github.com/ninolomata/cva6/tree/feat/hypervisor-mode)?

2. We're still experimenting with the new "integrate" action, so this is not very obvious. But the current integration causes a [port mismatch](https://iis-git.ee.ethz.ch/github-mirror/cheshire/-/jobs/1109219#L1965). Can you point the `base-ref` in [integration.yml](https://github.com/pulp-platform/cva6/blob/pulp-v1/.github/workflows/integration.yml) to a cheshire ref which integrates vCLIC? See [CONTRIBUTING-PULP.md](https://github.com/pulp-platform/cva6/blob/pulp-v1/CONTRIBUTING-PULP.md)

3. A more open question: Should we have an explicit `VCLIC` parameter or similar to enable/disable non-specified features? My concern is that H and CLIC have official RISC-V specs whereas vCLIC does not, so implicitly activating vCLIC when H and CLIC are enabled might lead to unexpected behavior.

2024-03-16 15:36 UTC, niwis commented on core/csr_regfile.sv
> +        if (CVA6Cfg.RVH) csr_rdata = {hgeie_q[riscv::XLEN-1:1], 1'b0};
These also look generally useful for H ext

2024-03-16 15:36 UTC, niwis commented on core/cva6.sv
> +  assign tracer_if.v              = v;
Can be combined with tracer H-support changes above

2024-10-31 03:49 UTC, niwis commented
Superseded by #55

2024-10-31 03:49 UTC, closed without merging